openapi: 3.0.0
info:
  title: Login API
  version: "1.0.0"
paths:
  /login:
    post:
      summary: Login endpoint
      requestBody:
        description: Login with email
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        '400':
          description: Bad Request - Invalid email
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /requestaccess:
    get:
      summary: Request access endpoint
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer <token>"
      responses:
        '200':
          description: Access granted
          content:
            application/json:
              schema:
                type: string
                example: "Access granted"
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                type: string